# Extend the default Keycloak base theme
parent=keycloak
import=common/keycloak

# Add your custom CSS file
styles=css/styles.css

# Optional: Override default text properties
# Custom login page title
# title=Autonoma Login